name: ninjaapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  cached_network_image: ^3.4.1
  file_picker: ^8.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  http: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  postgres: ^3.4.8
  process_run: ^1.1.0
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_migration: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
